"""empty message

Revision ID: 57680ba82e87
Revises: 088bf2649b51
Create Date: 2024-12-02 21:16:52.551718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57680ba82e87'
down_revision = '088bf2649b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surprises', sa.Integer(), nullable=True))
        batch_op.drop_column('questions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questions', sa.INTEGER(), nullable=True))
        batch_op.drop_column('surprises')

    # ### end Alembic commands ###
