"""empty message

Revision ID: 5921db068c3b
Revises: f99a19d280b2
Create Date: 2024-12-02 19:59:55.207183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5921db068c3b'
down_revision = 'f99a19d280b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laughs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grimaces', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('questions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('questions')
        batch_op.drop_column('blank')
        batch_op.drop_column('grimaces')
        batch_op.drop_column('laughs')

    # ### end Alembic commands ###
